#!/usr/bin/env tsx
/* Build-time content pull — property + teamMember + pillar + legalPage
 * → site/assets/data/{properties,team,services,legal}.json.
 *
 * Output JSON is byte-compatible with the Phase-2 shape so the frontend
 * needs no code change. Image URLs become Sanity CDN URLs with format=webp +
 * width=1200 presets. */
import dotenv from 'dotenv'
import fs from 'node:fs'
import path from 'node:path'
import {createClient} from '@sanity/client'
import imageUrlBuilder from '@sanity/image-url'

dotenv.config({path: path.resolve(__dirname, '../.env.local')})
dotenv.config({path: path.resolve(__dirname, '../.env')})

const ROOT = path.resolve(__dirname, '../..')
const SITE_DATA = path.join(ROOT, 'site/assets/data')

const projectId = process.env.SANITY_STUDIO_PROJECT_ID
const dataset = process.env.SANITY_STUDIO_DATASET || 'production'
if (!projectId) {
    console.error('SANITY_STUDIO_PROJECT_ID is not set.')
    process.exit(1)
}

const client = createClient({
    projectId,
    dataset,
    apiVersion: '2026-01-01',
    useCdn: true,
    token: process.env.SANITY_AUTH_TOKEN,
})

const builder = imageUrlBuilder(client)
function urlFor(source: any, width = 1200): string {
    if (!source) return ''
    return builder.image(source).width(width).auto('format').url()
}

function bs(v: any, lang: 'zh' | 'en'): string {
    if (!v) return ''
    return v[lang] || ''
}

function joinBlocks(blocks?: any[]): string {
    if (!blocks?.length) return ''
    return blocks
        .filter((b) => b._type === 'block')
        .map((b) => (b.children || []).map((c: any) => c.text || '').join(''))
        .join('\n\n')
}

function blocksToParas(blocks?: any[]): string[] {
    if (!blocks?.length) return []
    return blocks
        .filter((b) => b._type === 'block')
        .map((b) => (b.children || []).map((c: any) => c.text || '').join(''))
        .filter(Boolean)
}

async function main() {
    console.log(`Pulling docs from Sanity (${projectId}/${dataset})…`)

    /* ── properties.json ─────────────────────────────────────────────── */
    const props = await client.fetch(`*[_type == "property"] | order(orderRank asc) {
      "id": slug.current, category, transactionType, region, placeholder, image, title, location, price, area, beds, baths, description
    }`)
    const propertiesOut = {
        _note: 'AUTO-GENERATED by studio/migrate/pull-data.ts — source of truth is Sanity. Do not hand-edit.',
        items: props.map((p: any) => ({
            id: p.id,
            type: p.category,
            transactionType: p.transactionType || (p.category === 'rent' ? 'rent' : 'sale'),
            region: p.region || '',
            placeholder: !!p.placeholder,
            img: urlFor(p.image),
            titleZh: bs(p.title, 'zh'),
            titleEn: bs(p.title, 'en'),
            loc: bs(p.location, 'en') || bs(p.location, 'zh'),
            price: p.price?.formatted || '',
            area: bs(p.area, 'en') || bs(p.area, 'zh'),
            beds: p.beds || 0,
            baths: p.baths || 0,
            descZh: bs(p.description, 'zh'),
            descEn: bs(p.description, 'en'),
        })),
    }
    fs.writeFileSync(
        path.join(SITE_DATA, 'properties.json'),
        JSON.stringify(propertiesOut, null, 4) + '\n',
        'utf8',
    )
    console.log(`✓ wrote properties.json (${propertiesOut.items.length} items)`)

    /* ── team.json ───────────────────────────────────────────────────── */
    const team = await client.fetch(`*[_type == "teamMember"] | order(orderRank asc) {
      "id": slug.current, name, nameZh, role, initials, photo, bio
    }`)
    const teamOut = {
        _note: 'AUTO-GENERATED by studio/migrate/pull-data.ts.',
        members: team.map((m: any) => ({
            id: m.id,
            name: m.name,
            nameZh: m.nameZh || '',
            role: bs(m.role, 'en'),
            roleZh: bs(m.role, 'zh'),
            initials: m.initials,
            photo: urlFor(m.photo, 600),
        })),
    }
    fs.writeFileSync(
        path.join(SITE_DATA, 'team.json'),
        JSON.stringify(teamOut, null, 4) + '\n',
        'utf8',
    )
    console.log(`✓ wrote team.json (${teamOut.members.length} members)`)

    /* ── services.json ───────────────────────────────────────────────── */
    const pillars = await client.fetch(`*[_type == "pillar"] {
      "id": slug.current, icon, title, summary, heroImg, narrative, deliverables
    }`)
    /* Preserve docx → frontend order (real-estate / advertising / branding) */
    const SLUG_ORDER = ['real-estate', 'advertising', 'branding']
    pillars.sort((a: any, b: any) => SLUG_ORDER.indexOf(a.id) - SLUG_ORDER.indexOf(b.id))

    const servicesOut = {
        _note: 'AUTO-GENERATED by studio/migrate/pull-data.ts.',
        pillars: pillars.map((p: any) => ({
            id: p.id,
            icon: p.icon,
            title: bs(p.title, 'en'),
            titleZh: bs(p.title, 'zh'),
            summary: bs(p.summary, 'en'),
            summaryZh: bs(p.summary, 'zh'),
            heroImg: urlFor(p.heroImg, 1600),
            narrative: blocksToParas(p.narrative?.en),
            narrativeZh: blocksToParas(p.narrative?.zh),
            deliverables: (p.deliverables || []).map((d: any) => bs(d.label, 'en')),
            deliverablesZh: (p.deliverables || []).map((d: any) => bs(d.label, 'zh')),
            deliverableDescEn: (p.deliverables || []).map((d: any) => bs(d.description, 'en')),
            deliverableDescZh: (p.deliverables || []).map((d: any) => bs(d.description, 'zh')),
            caseStudies: [],
        })),
    }
    fs.writeFileSync(
        path.join(SITE_DATA, 'services.json'),
        JSON.stringify(servicesOut, null, 4) + '\n',
        'utf8',
    )
    console.log(`✓ wrote services.json (${servicesOut.pillars.length} pillars)`)

    /* ── legal.json ──────────────────────────────────────────────────── */
    const legal = await client.fetch(`*[_type == "legalPage"] {
      "id": slug.current, title, lastUpdated, intro, sections, cookieTable
    }`)
    const buildLegal = (lang: 'zh' | 'en') => {
        const out: any = {}
        for (const p of legal) {
            const entry: any = {
                title: bs(p.title, lang),
                lastUpdated: bs(p.lastUpdated, lang),
                intro: bs(p.intro, lang),
                sections: (p.sections || []).map((s: any) => ({
                    heading: bs(s.heading, lang),
                    body: blocksToParas(s.body?.[lang]),
                })),
            }
            if (p.id === 'cookies' && p.cookieTable) {
                entry.cookieTable = {
                    title: bs(p.cookieTable.title, lang),
                    rows: (p.cookieTable.rows || []).map((r: any) => ({
                        name: r.name,
                        purpose: bs(r.purpose, lang),
                        duration: r.duration,
                        category: bs(r.category, lang),
                    })),
                    columns: {
                        name: bs(p.cookieTable.columns?.name, lang),
                        purpose: bs(p.cookieTable.columns?.purpose, lang),
                        duration: bs(p.cookieTable.columns?.duration, lang),
                        category: bs(p.cookieTable.columns?.category, lang),
                    },
                }
            }
            out[p.id] = entry
        }
        return out
    }
    const legalOut = {
        _note: 'AUTO-GENERATED by studio/migrate/pull-data.ts.',
        zh: buildLegal('zh'),
        en: buildLegal('en'),
    }
    fs.writeFileSync(
        path.join(SITE_DATA, 'legal.json'),
        JSON.stringify(legalOut, null, 4) + '\n',
        'utf8',
    )
    console.log(`✓ wrote legal.json (${Object.keys(legalOut.zh).length} pages)`)

    /* ── projects.json ───────────────────────────────────────────────── */
    const projects = await client.fetch(`*[_type == "project"] | order(orderRank asc) {
      "id": slug.current, placeholder, name, status, tagline, location, propertyType,
      priceRange, totalUnits, developmentArea, launchYear, expectedDelivery,
      heroImage, gallery, description, keyFeatures
    }`)
    const projectsOut = {
        _note: 'AUTO-GENERATED by studio/migrate/pull-data.ts — source of truth is Sanity.',
        projects: projects.map((p: any) => ({
            id: p.id,
            placeholder: !!p.placeholder,
            nameZh: bs(p.name, 'zh'),
            nameEn: bs(p.name, 'en'),
            status: p.status,
            taglineZh: bs(p.tagline, 'zh'),
            taglineEn: bs(p.tagline, 'en'),
            location: bs(p.location, 'en') || bs(p.location, 'zh'),
            propertyTypeZh: bs(p.propertyType, 'zh'),
            propertyTypeEn: bs(p.propertyType, 'en'),
            priceRange: p.priceRange || '',
            totalUnits: p.totalUnits || 0,
            developmentAreaZh: bs(p.developmentArea, 'zh'),
            developmentAreaEn: bs(p.developmentArea, 'en'),
            launchYear: p.launchYear || null,
            expectedDeliveryZh: bs(p.expectedDelivery, 'zh'),
            expectedDeliveryEn: bs(p.expectedDelivery, 'en'),
            heroImg: urlFor(p.heroImage, 2000),
            gallery: (p.gallery || []).map((g: any) => urlFor(g, 1600)),
            descriptionZh: bs(p.description, 'zh'),
            descriptionEn: bs(p.description, 'en'),
            keyFeatures: (p.keyFeatures || []).map((f: any) => ({
                zh: f?.zh || '',
                en: f?.en || '',
            })),
        })),
    }
    fs.writeFileSync(
        path.join(SITE_DATA, 'projects.json'),
        JSON.stringify(projectsOut, null, 4) + '\n',
        'utf8',
    )
    console.log(`✓ wrote projects.json (${projectsOut.projects.length} projects)`)

    /* ── led-products.json ───────────────────────────────────────────── */
    const ledProducts = await client.fetch(`*[_type == "ledProduct"] | order(orderRank asc) {
      "id": model, model, placeholder, name, usage, pixelPitch, brightness, cabinetSize, salePrice, rentalPrice, image, note
    }`)
    const ledProductsOut = {
        _note: 'AUTO-GENERATED by studio/migrate/pull-data.ts — source of truth is Sanity.',
        products: ledProducts.map((p: any) => ({
            id: (p.id || p.model || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
            model: p.model || '',
            placeholder: !!p.placeholder,
            nameZh: bs(p.name, 'zh'),
            nameEn: bs(p.name, 'en'),
            usage: p.usage || 'indoor',
            pixelPitch: p.pixelPitch || '',
            brightness: p.brightness || '',
            cabinetSize: p.cabinetSize || '',
            salePrice: p.salePrice || '',
            rentalPrice: p.rentalPrice || '',
            img: urlFor(p.image, 800),
            noteZh: bs(p.note, 'zh'),
            noteEn: bs(p.note, 'en'),
        })),
    }
    fs.writeFileSync(
        path.join(SITE_DATA, 'led-products.json'),
        JSON.stringify(ledProductsOut, null, 4) + '\n',
        'utf8',
    )
    console.log(`✓ wrote led-products.json (${ledProductsOut.products.length} products)`)

    /* ── led-billboards.json ─────────────────────────────────────────── */
    const ledBillboards = await client.fetch(`*[_type == "ledBillboard"] | order(orderRank asc) {
      "id": code, code, placeholder, name, address, screenSize, dailyTraffic, availability, monthlyRate, image, mapUrl
    }`)
    const ledBillboardsOut = {
        _note: 'AUTO-GENERATED by studio/migrate/pull-data.ts — source of truth is Sanity.',
        billboards: ledBillboards.map((b: any) => ({
            id: (b.id || b.code || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
            code: b.code || '',
            placeholder: !!b.placeholder,
            nameZh: bs(b.name, 'zh'),
            nameEn: bs(b.name, 'en'),
            addressZh: bs(b.address, 'zh'),
            addressEn: bs(b.address, 'en'),
            screenSize: b.screenSize || '',
            dailyTraffic: b.dailyTraffic || '',
            availability: b.availability || 'coming',
            monthlyRate: b.monthlyRate || '',
            img: urlFor(b.image, 1200),
            mapUrl: b.mapUrl || '',
        })),
    }
    fs.writeFileSync(
        path.join(SITE_DATA, 'led-billboards.json'),
        JSON.stringify(ledBillboardsOut, null, 4) + '\n',
        'utf8',
    )
    console.log(`✓ wrote led-billboards.json (${ledBillboardsOut.billboards.length} billboards)`)

    /* ── news.json ───────────────────────────────────────────────────── */
    const news = await client.fetch(`*[_type == "newsArticle"] | order(publishedAt desc) {
      "id": slug.current, category, placeholder, publishedAt, title, excerpt, coverImage, body, source, sourceUrl
    }`)
    const newsOut = {
        _note: 'AUTO-GENERATED by studio/migrate/pull-data.ts — source of truth is Sanity. Do not hand-edit.',
        articles: news.map((a: any) => ({
            id: a.id,
            category: a.category,
            placeholder: !!a.placeholder,
            publishedAt: a.publishedAt,
            coverImg: urlFor(a.coverImage, 1600),
            titleZh: bs(a.title, 'zh'),
            titleEn: bs(a.title, 'en'),
            excerptZh: bs(a.excerpt, 'zh'),
            excerptEn: bs(a.excerpt, 'en'),
            bodyZh: blocksToParas(a.body?.zh),
            bodyEn: blocksToParas(a.body?.en),
            source: a.source || '',
            sourceUrl: a.sourceUrl || '',
        })),
    }
    fs.writeFileSync(
        path.join(SITE_DATA, 'news.json'),
        JSON.stringify(newsOut, null, 4) + '\n',
        'utf8',
    )
    console.log(`✓ wrote news.json (${newsOut.articles.length} articles)`)
}

main().catch((err) => {
    console.error(err)
    process.exit(1)
})
