/* JSON data-file store with optimistic locking.
 * Reads return {json, sha}; writes are atomic (tmp + rename), 4-space indent
 * to match the hand-written files, and refuse to proceed if the file changed
 * since the client loaded it (baseSha mismatch). */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const gitops = require('./gitops');

const SITE = path.join(gitops.REPO, 'site');
const DATA_DIR = path.join(SITE, 'assets', 'data');
const SETTINGS_JS = path.join(SITE, 'assets', 'js', 'settings.js');

function shaOf(buf) { return crypto.createHash('sha1').update(buf).digest('hex').slice(0, 12); }

function readFile(name) {
    const file = path.join(DATA_DIR, name);
    const raw = fs.readFileSync(file);
    return { json: JSON.parse(raw.toString('utf8')), sha: shaOf(raw), file };
}

function writeFile(name, json, baseSha) {
    const file = path.join(DATA_DIR, name);
    const current = fs.readFileSync(file);
    if (baseSha && shaOf(current) !== baseSha) {
        const err = new Error('conflict');
        err.code = 'CONFLICT';
        throw err;
    }
    const out = JSON.stringify(json, null, 4) + '\n';
    const tmp = file + '.tmp';
    fs.writeFileSync(tmp, out);
    fs.renameSync(tmp, file);
    return shaOf(Buffer.from(out));
}

/* ── settings.js (generated file consumed by the public site) ── */
const SETTINGS_DEFAULTS = {
    whatsapp: '260964813736',
    ga4Id: '',
    pixelId: '',
    social: { instagram: '', facebook: '', linkedin: '', youtube: '' }
};

function readSettings() {
    try {
        const raw = fs.readFileSync(SETTINGS_JS, 'utf8');
        const m = raw.match(/window\.ROOFY_SETTINGS\s*=\s*(\{[\s\S]*?\});/);
        if (m) {
            const parsed = JSON.parse(m[1]);
            return {
                json: Object.assign({}, SETTINGS_DEFAULTS, parsed,
                    { social: Object.assign({}, SETTINGS_DEFAULTS.social, parsed.social || {}) }),
                sha: shaOf(Buffer.from(raw))
            };
        }
    } catch (e) { /* fall through to defaults */ }
    return { json: JSON.parse(JSON.stringify(SETTINGS_DEFAULTS)), sha: '' };
}

function writeSettings(json, baseSha) {
    let currentSha = '';
    try { currentSha = shaOf(fs.readFileSync(SETTINGS_JS)); } catch (e) { /* new file */ }
    if (baseSha && currentSha && currentSha !== baseSha) {
        const err = new Error('conflict');
        err.code = 'CONFLICT';
        throw err;
    }
    const out = '/* Generated by ROOFY Admin (' + new Date().toISOString().slice(0, 10) + ') — do not edit by hand.\n' +
        ' * Site settings consumed by partials.js (WhatsApp, footer socials) and analytics.js (GA4/Pixel). */\n' +
        'window.ROOFY_SETTINGS = ' + JSON.stringify(json, null, 4) + ';\n';
    const tmp = SETTINGS_JS + '.tmp';
    fs.writeFileSync(tmp, out);
    fs.renameSync(tmp, SETTINGS_JS);
    return shaOf(Buffer.from(out));
}

/* Relative-to-repo paths for git commits. */
function repoRel(abs) { return path.relative(gitops.REPO, abs); }

module.exports = {
    SITE, DATA_DIR, SETTINGS_JS, readFile, writeFile, readSettings, writeSettings, repoRel, shaOf
};
